### ISSUE TITLE
Cannot update a document with properties to remove

### ISSUE THREAD

**Issue by Kevosis** [neo9/n9-mongo-client#1]
https://github.com/neo9/n9-mongo-client/blob/83cb24d65975e86ad3b410fad2da64a1d8ed124d/src/client.ts#L500

While updating a document, we should be able to create, update or delete a property.

Only operator $set is used then we cannot delete a property

**Comment by BenjD90** [comment]
@Kevosis Only bulk operations are affected ;)

**Comment by Kevosis** [comment]
I just submitted a PR to fix that #2

**Comment by BenjD90** [comment]
This issue affect only first level properties, sub properties are overridden by $set mechanism.

**Comment by BenjD90** [comment]
Merge with #3
